// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace VirgoGameplayTags
{
	/* Input Tags */
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Unequip);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack);

	/* Player Tags */
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Sword);

	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Sword);

	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Attack_Sword);
}